print("Dog Breed: German Shepherd")
print("Dog Breed: Golden Retriever")
print("Dog Breed: Bulldog")
print("Dog Breed: Poodle")
print("Dog Breed: Beagle")
print("Dog Breed: Rottweiler")
print("Dog Breed: Siberian Husky")
print("Dog Breed: Boxer")
print("Dog Breed: Dachshund")
print("Dog Breed: Doberman")  # 10 ცვლადი ძაღლის სახეობის ბროოოსკიიიი  GOA N1 ! 